package Forms;

import Entities.Producto;
import Entities.Proveedor;
import java.util.List;
import EntradaXProducto.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Tejada
 */
public class EntradaxProducto extends javax.swing.JFrame {
//    p.getIdProducto()),p.getProducto(),p.getIdMarca().getMarca(),
//                                    p.getIdCategoria().getCategoria(),p.getDescripcion()
    String []titulos = {"codigo","producto","marca","categoria","descripcion"};
    int LidProducto;
    Date fechaActual = new Date();
    DateFormat formatoFecha = null;
    
    Utilidades utilidades = new Utilidades();
    ArrayList<Productos> lpn;
    public EntradaxProducto() {
        initComponents();
        formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        
        this.lbFecha.setText(formatoFecha.format(fechaActual));
        lpn=new ArrayList<>();
        llenarproveedores();
        llenarcomboboxcant();
        this.tbNombreP.setEnabled(false);
        this.tbDireccionP.setEnabled(false);
        this.tbtelefonop.setEnabled(false);
        this.lblNombreP.setEnabled(false);
        this.lblDireccionP.setEnabled(false);
        this.lbltelefonoP.setEnabled(false);
        utilidades.fillJTable(this.TbBProduct,"Producto", titulos);
        this.TbBProduct.setDefaultEditor(Object.class,null);
        deshabilitarPP();
        utilidades.setScreenCentered(this);
//        this.setExtendedState(EntradaxProducto.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNGproducto = new javax.swing.ButtonGroup();
        MenuTableBusq = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelProducto = new javax.swing.JPanel();
        tbNombre = new javax.swing.JTextField();
        tbMarca = new javax.swing.JTextField();
        tbPrecioU = new javax.swing.JTextField();
        lbNonbre = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbMarca = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDescripcion = new javax.swing.JTextArea();
        lbDescripcion = new javax.swing.JLabel();
        lbFechaVencimiento = new javax.swing.JLabel();
        dpFechaVencimiento = new org.jdesktop.swingx.JXDatePicker();
        cbcant = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarProd = new javax.swing.JButton();
        TBCategoria = new javax.swing.JTextField();
        lbFechaVencimiento1 = new javax.swing.JLabel();
        panelProveedor = new javax.swing.JPanel();
        CBProveedores = new javax.swing.JComboBox<>();
        RBNuevoProv = new javax.swing.JRadioButton();
        tbNombreP = new javax.swing.JTextField();
        tbDireccionP = new javax.swing.JTextField();
        lblNombreP = new javax.swing.JLabel();
        lblDireccionP = new javax.swing.JLabel();
        tbtelefonop = new javax.swing.JTextField();
        lbltelefonoP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgvEntradas = new javax.swing.JTable();
        btGuardarEntrada = new javax.swing.JButton();
        btEliminarProducto = new javax.swing.JButton();
        panelRegistro = new javax.swing.JPanel();
        lbFecha = new javax.swing.JLabel();
        PanelBusqueda = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbBProduct = new javax.swing.JTable();
        btnBuscarP = new javax.swing.JButton();
        txtBusquedaP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tbRepresentante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tbduirep = new javax.swing.JTextField();
        lbLogOut = new javax.swing.JLabel();

        jMenuItem1.setText("Seleccionar Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuTableBusq.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compras");
        setResizable(false);

        panelProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTO ENTRANTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        tbNombre.setEditable(false);

        tbMarca.setEditable(false);
        tbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMarcaActionPerformed(evt);
            }
        });

        tbPrecioU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbPrecioUKeyTyped(evt);
            }
        });

        lbNonbre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNonbre.setText("Nombre");

        lbPrecio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPrecio.setText("Precio unitario");

        lbMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMarca.setText("Marca");

        tbDescripcion.setEditable(false);
        tbDescripcion.setColumns(20);
        tbDescripcion.setRows(5);
        jScrollPane1.setViewportView(tbDescripcion);

        lbDescripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDescripcion.setText("Descripcion");

        lbFechaVencimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFechaVencimiento.setText("Vencimiento:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Cantidad");

        btnAgregarProd.setBackground(new java.awt.Color(102, 102, 255));
        btnAgregarProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarProd.setText("Agregar A la compra");
        btnAgregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProdActionPerformed(evt);
            }
        });

        TBCategoria.setEditable(false);

        lbFechaVencimiento1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFechaVencimiento1.setText("Categoria");

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescripcion)
                    .addComponent(lbFechaVencimiento1)
                    .addComponent(lbNonbre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelProductoLayout.createSequentialGroup()
                                .addComponent(lbFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dpFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProductoLayout.createSequentialGroup()
                                .addComponent(lbPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProductoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbcant, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createSequentialGroup()
                        .addComponent(btnAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNonbre)
                            .addComponent(tbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMarca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFechaVencimiento1))
                        .addGap(18, 18, 18)
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDescripcion)))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbPrecioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPrecio))
                        .addGap(18, 18, 18)
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFechaVencimiento)
                            .addComponent(dpFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        panelProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECCIONE EL PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 51, 51))); // NOI18N

        RBNuevoProv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RBNuevoProv.setText("Nuevo Porveedor");
        RBNuevoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBNuevoProvActionPerformed(evt);
            }
        });

        tbNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNombrePActionPerformed(evt);
            }
        });
        tbNombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbNombrePKeyTyped(evt);
            }
        });

        lblNombreP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreP.setText("Nombre:");

        lblDireccionP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDireccionP.setText("Direccion:");

        tbtelefonop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbtelefonopKeyTyped(evt);
            }
        });

        lbltelefonoP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltelefonoP.setText("Telefono:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Seleccione ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("O ingrese");

        javax.swing.GroupLayout panelProveedorLayout = new javax.swing.GroupLayout(panelProveedor);
        panelProveedor.setLayout(panelProveedorLayout);
        panelProveedorLayout.setHorizontalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(CBProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RBNuevoProv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelProveedorLayout.createSequentialGroup()
                            .addComponent(lblNombreP)
                            .addGap(18, 18, 18)
                            .addComponent(tbNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelProveedorLayout.createSequentialGroup()
                            .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDireccionP)
                                .addComponent(lbltelefonoP))
                            .addGap(18, 18, 18)
                            .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tbDireccionP)
                                .addComponent(tbtelefonop, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        panelProveedorLayout.setVerticalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBNuevoProv)
                .addGap(18, 18, 18)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbDireccionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccionP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtelefonop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltelefonoP))
                .addGap(29, 29, 29))
        );

        dgvEntradas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dgvEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(dgvEntradas);

        btGuardarEntrada.setBackground(new java.awt.Color(102, 255, 102));
        btGuardarEntrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGuardarEntrada.setText("Guardar Entradas");
        btGuardarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarEntradaActionPerformed(evt);
            }
        });

        btEliminarProducto.setBackground(new java.awt.Color(255, 102, 102));
        btEliminarProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEliminarProducto.setText("Eliminar Producto");
        btEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarProductoActionPerformed(evt);
            }
        });

        panelRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de expedicion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFecha.setText("12-12-12");

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbFecha))
        );

        PanelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busque Productos existentes y seleccione ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 204))); // NOI18N

        TbBProduct.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TbBProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TbBProduct.setComponentPopupMenu(MenuTableBusq);
        TbBProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbBProductMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TbBProduct);

        btnBuscarP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarP.setText("buscar");
        btnBuscarP.setActionCommand("Buscar");
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });

        txtBusquedaP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaPKeyTyped(evt);
            }
        });

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBusquedaLayout = new javax.swing.GroupLayout(PanelBusqueda);
        PanelBusqueda.setLayout(PanelBusquedaLayout);
        PanelBusquedaLayout.setHorizontalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addComponent(txtBusquedaP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        PanelBusquedaLayout.setVerticalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBusquedaLayout.createSequentialGroup()
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusquedaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarP)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("+ Agregar producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Representante del proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 0))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombre del Representante:");

        tbRepresentante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbRepresentanteKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Dui del representante:");

        tbduirep.setText(" ");
        tbduirep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbduirepKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tbRepresentante, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5))
                    .addComponent(tbduirep, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbduirep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        lbLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        lbLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(350, 350, 350)
                                .addComponent(btGuardarEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEliminarProducto)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLogOut))
                        .addGap(27, 27, 27)
                        .addComponent(panelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGuardarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btGuardarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarEntradaActionPerformed
        int x=0;
        if(validarCamposGuardarEnt()==true){
            if(this.RBNuevoProv.isSelected()==true){
                x=utilidades.crearDetCompra(
                        this.lpn,utilidades.insertProveedor(this.tbNombreP.getText(),this.tbDireccionP.getText(),this.tbtelefonop.getText()),
                        fechaActual,this.tbRepresentante.getText(),this.tbduirep.getText());
                
            }
            else if(this.RBNuevoProv.isSelected()==false){
                x=utilidades.crearDetCompra(
                        this.lpn,utilidades.findProvbyname(this.CBProveedores.getSelectedItem().toString()),
                        fechaActual,this.tbRepresentante.getText(),this.tbduirep.getText());
            }
            if(x!=-1){
                JOptionPane.showMessageDialog(null, "Registro existoso","Registro",JOptionPane.INFORMATION_MESSAGE);
                clearforNew();
                deshabilitarPP();
                this.dgvEntradas.removeAll();
            }
        }
        else if(validarCamposGuardarEnt()==false){
            JOptionPane.showMessageDialog(null, "Algun campo esta vacio","Registro",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btGuardarEntradaActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        if(this.txtBusquedaP.getText().length()!=0){
            utilidades.fillJTable(this.TbBProduct,"Producto","producto",this.txtBusquedaP.getText(), titulos);
            this.TbBProduct.setDefaultEditor(Object.class,null);
        }
        else if(this.txtBusquedaP.getText().length()==0){
            utilidades.fillJTable(this.TbBProduct,"Producto", titulos);
            this.TbBProduct.setDefaultEditor(Object.class,null);
        }
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void tbNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNombrePActionPerformed

    private void RBNuevoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBNuevoProvActionPerformed
        if(this.RBNuevoProv.isSelected()==true){
            this.CBProveedores.setEnabled(false);
            this.tbNombreP.setEnabled(true);
            this.tbDireccionP.setEnabled(true);
            this.tbtelefonop.setEnabled(true);
            this.lblNombreP.setEnabled(true);
            this.lblDireccionP.setEnabled(true);
            this.lbltelefonoP.setEnabled(true);
        }
        else if(this.RBNuevoProv.isSelected()==false){
            this.CBProveedores.setEnabled(true);
            this.tbNombreP.setEnabled(false);
            this.tbDireccionP.setEnabled(false);
            this.tbtelefonop.setEnabled(false);
            this.lblNombreP.setEnabled(false);
            this.lblDireccionP.setEnabled(false);
            this.lbltelefonoP.setEnabled(false);
        }
    }//GEN-LAST:event_RBNuevoProvActionPerformed

    private void btnAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProdActionPerformed
        if(validarCamposAggProd()==true){
            int existente;
            existente=utilidades.buscarProdEnArrayEP(lpn,LidProducto);
            String []tituloss = {"id","producto","marca","categoria","descripcion","precio","cantidad","caducidad"};
            if(existente==-1){
                
                lpn.add(new Productos(LidProducto,this.TBCategoria.getText(),this.tbMarca.getText(),
                        this.tbNombre.getText(),this.tbDescripcion.getText(),
                        Double.parseDouble(this.tbPrecioU.getText()),
                        Integer.parseInt(this.cbcant.getSelectedItem().toString()),this.dpFechaVencimiento.getDate()));
                utilidades.llenarJtablePE(this.lpn, this.dgvEntradas, tituloss);
            }else if(existente!=-1){
                int r= JOptionPane.showConfirmDialog(
                        null,"AVISO!ya tiene un producto en lista de compra si continua se le aumentara el producto, se editara la caducidad y el precio. ¿desea continuar?","CONTINUAR!",JOptionPane.YES_NO_OPTION);
                if(r==JOptionPane.YES_OPTION){
                    lpn.get(existente).
                            setCantidad(lpn.get(existente).getCantidad()+
                                    Integer.parseInt(this.cbcant.getSelectedItem().toString()));
                    lpn.get(existente).setFechavencimiento(this.dpFechaVencimiento.getDate());
                    lpn.get(existente).setPrecio(Double.parseDouble(this.tbPrecioU.getText()));
                    utilidades.llenarJtablePE(this.lpn, this.dgvEntradas, tituloss);
                }
                else if(r==JOptionPane.NO_OPTION){
                    
                }
                else if(r==JOptionPane.CLOSED_OPTION){
                    
                }
            }
        }
        else if(validarCamposAggProd()==false){
            JOptionPane.showMessageDialog(null, "Algun campo esta vacio","Registro",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarProdActionPerformed

    private void tbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMarcaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IProducto prod = new IProducto();
        Object[] options = { "REGRESAR"};
        JOptionPane.showOptionDialog(null,prod.getContentPane(), "Productos",
                JOptionPane.DEFAULT_OPTION, JOptionPane.DEFAULT_OPTION,
                null, options, options[0]);
        utilidades.fillJTable(this.TbBProduct,"Producto", titulos);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TbBProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbBProductMouseClicked
        habilitarPP();
        int fila = this.TbBProduct.getSelectedRow();
        List<Producto> listado1=utilidades.obtenerproducto("Producto",fila+1,"idProducto");
        LidProducto=listado1.get(0).getIdProducto();
        this.tbNombre.setText(listado1.get(0).getProducto());
        this.tbMarca.setText(listado1.get(0).getIdMarca().getMarca());
        this.tbPrecioU.setText(Double.toString(listado1.get(0).getPrecio()));
        this.tbDescripcion.setText(listado1.get(0).getDescripcion());
        this.TBCategoria.setText(listado1.get(0).getIdCategoria().getCategoria());
    }//GEN-LAST:event_TbBProductMouseClicked

    private void tbPrecioUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPrecioUKeyTyped
        if((!Character.isDigit(evt.getKeyChar())&&(evt.getKeyChar()!='.'))) {
            evt.consume();
        }
        if((evt.getKeyChar()=='.')&&(this.tbPrecioU.getText().contains("."))) {
            evt.consume();
        }
        if(this.tbPrecioU.getText().length()>10){
            evt.consume();
        }
    }//GEN-LAST:event_tbPrecioUKeyTyped

    private void tbNombrePKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbNombrePKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar())&&(evt.getKeyChar()!=' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_tbNombrePKeyTyped

    private void tbtelefonopKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbtelefonopKeyTyped
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
        if(this.tbtelefonop.getText().length()>12) {
            evt.consume();
        }
    }//GEN-LAST:event_tbtelefonopKeyTyped

    private void tbRepresentanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbRepresentanteKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar())&&(evt.getKeyChar()!=' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_tbRepresentanteKeyTyped

    private void tbduirepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbduirepKeyTyped
        if((!Character.isDigit(evt.getKeyChar())&&(evt.getKeyChar()!='-'))) {
            evt.consume();
        }
        if((evt.getKeyChar()=='-')&&(this.tbduirep.getText().contains("-"))) {
            evt.consume();
        }
        if(this.tbduirep.getText().length()>12) {
            evt.consume();
        }
    }//GEN-LAST:event_tbduirepKeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        utilidades.fillJTable(this.TbBProduct,"Producto", titulos);
        this.TbBProduct.setDefaultEditor(Object.class,null);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtBusquedaPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaPKeyTyped
        utilidades.fillJTable(this.TbBProduct,"Producto","producto",this.txtBusquedaP.getText(), titulos);
        this.TbBProduct.setDefaultEditor(Object.class,null);
    }//GEN-LAST:event_txtBusquedaPKeyTyped

    private void btEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarProductoActionPerformed
        int r= JOptionPane.showConfirmDialog(null,"confirmar eliminacion de producto","CONTINUAR!",JOptionPane.YES_NO_OPTION);
        if(r==JOptionPane.YES_OPTION){
            String []tituloss = {"id","producto","marca","categoria","descripcion","precio","cantidad","caducidad"};
            int fila = this.dgvEntradas.getSelectedRow();
            int idproducto = Integer.parseInt(this.dgvEntradas.getValueAt(fila,0).toString());
            utilidades.eliminarProdPE(this.lpn, idproducto);
            utilidades.llenarJtablePE(this.lpn, this.dgvEntradas, tituloss);
        }
        else if(r==JOptionPane.NO_OPTION){
            
        }
        else if(r==JOptionPane.CLOSED_OPTION){
            
        }

    }//GEN-LAST:event_btEliminarProductoActionPerformed

    private void lbLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogOutMouseClicked
        if (LogIn.usuario.getIdRol().getIdRol() == 1) new PrincipalAdmin().setVisible(true);
        else new PrincipalEmpleado().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbLogOutMouseClicked
    public void clearforNew(){
        this.lpn=null;
        this.tbNombre.setText("");
        this.tbDescripcion.setText("");
        this.tbDireccionP.setText("");
        this.tbMarca.setText("");
        this.tbPrecioU.setText("");
        this.tbRepresentante.setText("");
        this.tbduirep.setText("");
        this.TBCategoria.setText("");
        this.tbNombreP.setText("");
        this.tbDireccionP.setText("");
        this.tbtelefonop.setText("");
        lpn=new ArrayList<>();
    }
    public void deshabilitarPP(){
        for(int i=0;i<this.panelProducto.getComponents().length;i++) {
            this.panelProducto.getComponent(i).setEnabled(false);
        }
    }
    public void habilitarPP(){
        for(int i=0;i<this.panelProducto.getComponents().length;i++) {
            this.panelProducto.getComponent(i).setEnabled(true);
        }
    }
    public void habilitarPB(){
        for(int i=0;i<this.PanelBusqueda.getComponents().length;i++) {
            this.PanelBusqueda.getComponent(i).setEnabled(true);
        }
        this.TbBProduct.setEnabled(true);
        this.TbBProduct.setVisible(true);
        this.TbBProduct.setDefaultEditor(Object.class,null);
    }
    public void deshabilitarPB(){
        for(int i=0;i<this.PanelBusqueda.getComponents().length;i++) {
            this.PanelBusqueda.getComponent(i).setEnabled(false);
        }
        this.TbBProduct.setEnabled(false);
        this.TbBProduct.setVisible(false);
        this.TbBProduct.setDefaultEditor(Object.class,null);
    }
    public void llenarproveedores(){
        this.CBProveedores.removeAllItems();
        for(Proveedor p : utilidades.fillcomboboxp()){
            this.CBProveedores.addItem(p.getProveedor());
        }
    }
    public void llenarcomboboxcant(){
        this.cbcant.removeAllItems();
        for (int i = 1; i < 26; i++) {
            this.cbcant.addItem(Integer.toString(i));
        }
    }
    public boolean validarCamposAggProd(){
        boolean validado=false;
        if((this.tbNombre.getText().length()!=0)&&(this.TBCategoria.getText().length()!=0)&&
                (this.tbDescripcion.getText().length()!=0)&&(this.tbMarca.getText().length()!=0)&&
                (this.tbPrecioU.getText().length()!=0)&&(this.dpFechaVencimiento.getDate()!=null)){
            validado=true;
        }
        else if((this.tbNombre.getText().length()==0)||(this.TBCategoria.getText().length()==0)||
                (this.tbDescripcion.getText().length()==0)||(this.tbMarca.getText().length()==0)||
                (this.tbPrecioU.getText().length()==0)||(this.dpFechaVencimiento.getDate()==null)){
            validado=false;
        }
        return validado;
    }
    public boolean validarCamposGuardarEnt(){
        boolean validado=false;
        if(this.RBNuevoProv.isSelected()==true){
            if((this.tbNombreP.getText().length()!=0)&&
                    (this.tbDireccionP.getText().length()!=0)&&(this.tbtelefonop.getText().length()!=0)
                    &&(validarrepresentante()==true)&&(this.dgvEntradas.getRowCount()>0)){
                validado=true;
            }
        }
        else if(this.RBNuevoProv.isSelected()==false){
            if((validarrepresentante()==true)&&(this.dgvEntradas.getRowCount()>0)){
                validado=true;}
        }
        else{validado=false;}
        return validado;}
    public boolean validarrepresentante(){
        boolean validado=false;
        if((this.tbRepresentante.getText().length()!=0)&&
                (this.tbduirep.getText().length()!=0)){
            validado=true;
        }
        else if((this.tbRepresentante.getText().length()==0)||
                (this.tbduirep.getText().length()==0)){
            validado=false;
        }
        return validado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaxProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaxProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaxProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaxProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaxProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTNGproducto;
    private javax.swing.JComboBox<String> CBProveedores;
    private javax.swing.JPopupMenu MenuTableBusq;
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JRadioButton RBNuevoProv;
    private javax.swing.JTextField TBCategoria;
    private javax.swing.JTable TbBProduct;
    private javax.swing.JButton btEliminarProducto;
    private javax.swing.JButton btGuardarEntrada;
    private javax.swing.JButton btnAgregarProd;
    private javax.swing.JButton btnBuscarP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbcant;
    private javax.swing.JTable dgvEntradas;
    private org.jdesktop.swingx.JXDatePicker dpFechaVencimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbFechaVencimiento;
    private javax.swing.JLabel lbFechaVencimiento1;
    private javax.swing.JLabel lbLogOut;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbNonbre;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lblDireccionP;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lbltelefonoP;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JPanel panelProveedor;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JTextArea tbDescripcion;
    private javax.swing.JTextField tbDireccionP;
    private javax.swing.JTextField tbMarca;
    private javax.swing.JTextField tbNombre;
    private javax.swing.JTextField tbNombreP;
    private javax.swing.JTextField tbPrecioU;
    private javax.swing.JTextField tbRepresentante;
    private javax.swing.JTextField tbduirep;
    private javax.swing.JTextField tbtelefonop;
    private javax.swing.JTextField txtBusquedaP;
    // End of variables declaration//GEN-END:variables
}
